### ISSUE TITLE
Mode Spec

### ISSUE THREAD

**Issue by JMounier** [JMounier/Aegina#413]
- une commande pour changer de mode (normal, spec et/ou fly) :
 - si le fly : 
   - [x] désactiver la gravité.
    - [x] pouvoir aller vers le haut/bas et avoir plus de delta pour l'angle de vue.
    - problèmes : on risque de voir le model et il y aura l'interface donc vue dégelasse pour la video.
 - si mode spec : 
   - [x] Comme pour le fly mais avec une touche pour activer/désactiver les GUIs sauf le chat.
    - [x] Désactiver le model du perso et son collider si ça pose pas trop de problèmes.
    - [x] possibilité de choisir la vitesse de deplacement (x1 , x3, x10)

**Comment by JMounier** [comment]
peut être ajouter un système d'orbit en spec ?

**Comment by flomonster** [comment]
@JMounier Heu c'est chaud de faire un truc sans trop hardcoder une prise de vue (faire un truc pour n'importe quelle *rayon / centre / angle* etc... c'est chaud surtout en une commande...)

------------------------------

Sinon revoyez l'indentation de vos dernier commit car c'est pas ouf (alignement, acolade...).
*Ps :* Mono Dev ??

**Comment by JMounier** [comment]
je pensais a un truc genre :
- /center <dir> <dist> : pour set le centre de l'orbit a dist unités suivant dir 
- /orbit [+|-] [delta]  pour lancer la rotation de ± delta degré autour du centre

---------

évidement que c'est mono develop depuis quand j'ai un pc ^^

**Comment by flomonster** [comment]
Ouai pourquoi pas... Apres c'est pas essentiel a mon gout ... (Il manque un parametre de *vitesse*....)

-------------

Lol ^^

**Comment by JMounier** [comment]
je m'occupe de l'orbit demain
