### ISSUE TITLE
Filme de la generation

### ISSUE THREAD

**Issue by JMounier** [JMounier/Aegina#414]
Faire une version où les lignes du graphe sont visibles :
 - reprendre l'utilisation des ligne renderer ou un truc du genre 
normalement c'est rapide mais il faut le mode spec pour pouvoir le filmer correctement.

**Comment by flomonster** [comment]
Il faudrait reprendre les 4 phases de la presentation.
On pourait faire un deplacement circulaire autour de l'ile avec un fondu entre chaque phase (mais le deplacement doit rester fluide).
*PS: * Je sais pas si je suis clair...

**Comment by JMounier** [comment]
je pensais rush en mode spec sur un endroit vide ^^

**Comment by JMounier** [comment]
avec un petit /orbit pour créer l'otite en face de toi ^^

**Comment by JMounier** [comment]
on abort ça du coup ??

**Comment by flomonster** [comment]
Oui on abort...
