### ISSUE TITLE
Video : Demo

### ISSUE THREAD

**Issue by JMounier** [JMounier/Aegina#416]
Listez ici les éléments à montrer (ici c'est la forme finale de la vid qui est décrite) :
- 1ère Partie : (±10 sec depend si ton pote fait un truc ou pas)
 - logo (Aegina, AIM2, epita, unity)
 - une animation de Pegi 3   :P
 - une petite truc d'intro badass (faite par ton pote flo si possible avec genre ille qui s'éveil sur une île ^^)
 - titre + re notre logo (si possible qui s'enchaîne bien avec le menu du jeu)
- 2éme Partie (survie): ( ± 45 sec)
 - debut du jeu (premiere scene + personnalisation du perso)
 - inventaire (craft, drag & drop, coffre, équipements)
 - récolte (nettoyage de tous les biome en accéléré)
 - Boss fight
 - ...

- 3éme Partie (combat) : (± 45 sec)
 - gros fight (en vue spec)
 - Popo et effect ( genre un gros saut avec dash vers le bas etc ...)
 - ...

**Comment by flomonster** [comment]
Je peux apporter plus de precision... Pour la 2eme partie, ca serai super bien si on fait un timelaps (Ca implique que le cameraman ne bouge pas du tout...). Sur l'ile vous nettoyer tout et apres vous construisez un camp. Cependant pendant le tournage il faudra le faire assez *lentement* (genre 15 comme ca on peut voir le cycle jour nuit...). De plus quand la nuit tombe vous pouvez commencer a emttre des torches feu de camp... (Uniquement quand la nuit tombe)...

Apres en conseil general pour le cameraman il faut pas essayer de faire des scene de ouf en se deplacant de partour il faut faire des truc lisse lent... Ca facilite de ouf le montage et ca rend bcp mieux  au final :D
